### ISSUE TITLE
Blue border is visible in buttons

### ISSUE THREAD

**Issue by onmax** [nimiq/nimiq-style#2]
![image](https://user-images.githubusercontent.com/22072217/48217482-c2050880-e387-11e8-9b4a-5088c7c7df14.png)

**Comment by onmax** [comment]
In .nq-button adding outline: 0; should work

**Comment by sisou** [comment]
I think keeping the outline for accessibility reasons and keyboard navigation is a good idea.
Interested in other opinions, though.

**Comment by sisou** [comment]
Or needs to be replaced with a `:focus` state that is easily visible.

**Comment by onmax** [comment]
Do you want me to try that?
